name: ribasim

channels:
  - conda-forge

dependencies:
  - black
  - black-jupyter
  - build
  - datamodel-code-generator
  - geopandas
  - jupyterlab
  - matplotlib
  - mypy
  - pandas!=2.1.0
  - pandas-stubs
  - pandera
  - pip
  - pip:
    - quartodoc
  - pre-commit
  - pyarrow
  - pydantic
  - pyogrio
  - pytest
  - pytest-cov
  - python>=3.9
  - ruff
  - shapely>=2.0
  - tomli
  - tomli-w
  - twine
  - xarray
  - xmipy
