starttime = 2019-01-01
endtime = 2019-03-01
# endtime = 2021-01-01

add_levelcontrol = false
run_modflow = false

# [s] Î”t for periodic update frequency, including user horizons
update_timestep = 86400.0
saveat = 86400.0

# path to the UGrid NetCDF with the network, profiles, user and forcing data
# lsw_ids = [151358]
# lsw_ids = [151358, 151371, 151309]
# lsw_ids = [200164]
lsw_ids = [200164, 200165]

forcing = "data/input/6/forcing.arrow"
state = "data/input/6/state.arrow"
static = "data/input/6/static.arrow"
profile = "data/input/6/profile.arrow"
network_path = "data/input/6/network.ply"

# state = "data/input/6/state-mozart.arrow"
# static = "data/input/6/static-mozart.arrow"
# profile = "data/input/6/profile-mozart.arrow"

# entire district around Hupsel
# lsw_ids = [
#        150006, 150016, 150017, 150018, 151145, 151191, 151196, 151208,
#        151209, 151213, 151216, 151220, 151225, 151228, 151229, 151232,
#        151233, 151235, 151236, 151240, 151241, 151242, 151246, 151248,
#        151249, 151250, 151251, 151259, 151260, 151261, 151264, 151265,
#        151266, 151267, 151270, 151278, 151279, 151280, 151281, 151282,
#        151284, 151286, 151287, 151290, 151295, 151297, 151301, 151304,
#        151305, 151309, 151310, 151313, 151314, 151316, 151319, 151320,
#        151323, 151324, 151325, 151327, 151331, 151334, 151337, 151340,
#        151341, 151342, 151348, 151349, 151352, 151353, 151357, 151358,
#        151361, 151367, 151368, 151369, 151371, 151372, 151378, 151386,
#        151388, 151394, 151406, 151407, 151408, 151410, 151431, 151432,
#        151433, 151434, 151440, 151443, 151449, 151451, 151454, 151455,
#        151460, 151462, 151463, 151468, 151473, 151479, 151481, 151491,
#        151500, 151520, 151524, 151525, 151532, 151535, 151536, 151540,
#        151544, 151547, 151548, 151552, 151565, 151571, 151581, 151587,
#        151595, 151598, 151610, 151613, 151626, 151627, 151629, 151633,
#        151690, 151707
# ]

# entire district around de Tol
# lsw_ids = [
#        200011, 200025, 200028, 200031, 200032, 200033, 200034, 200035,
#        200036, 200088, 200093, 200099, 200101, 200105, 200111, 200120,
#        200121, 200122, 200142, 200143, 200144, 200147, 200148, 200149,
#        200150, 200151, 200154, 200155, 200156, 200164, 200165, 991024
# ]

[modflow]
simulation = "data/hupsel-steady-state/mfsim.nam"
mode = "sequential"
timestep = 86400.0

[modflow.models]

[modflow.models.gwf]
type = "gwf"
dataset = "d:/repo/bach/modflow/volume_level_profile-hupsel.nc"
basins = "lsw_id"

[[modflow.models.gwf.bounds]]
river = "RIV_P"
drain = "DRN_P"
profile = "profile_primary"

[[modflow.models.gwf.bounds]]
river = "RIV_S"
drain = "DRN_S"
profile = "profile_secondary"

[[modflow.models.gwf.bounds]]
drain = "DRN_T"
profile = "profile_tertiary"
