name = "libribasim"
uuid = "f319f290-633d-4573-adfe-d6d5548b6388"
authors = ["Deltares and contributors"]
version = "0.1.0"

[deps]
Ribasim = "aac5e3d9-0b8f-4d4f-8241-b1a7a9632635"
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
