name = "Ribasim"
uuid = "aac5e3d9-0b8f-4d4f-8241-b1a7a9632635"
authors = ["Deltares and contributors <ribasim.info@deltares.nl>"]
manifest = "../Manifest.toml"
version = "2025.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Legolas = "741b9549-f6ed-4911-9fbf-4a1c0c97f0cd"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
OrdinaryDiffEqBDF = "6ad6398a-0878-4a85-9266-38940aa047c8"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqSDIRK = "2d112036-d095-4a1e-ab9a-08536f3ecdbf"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
RibasimMakieExt = ["Makie", "DataFrames"]

[compat]
Accessors = "0.1"
Aqua = "0.8"
Arrow = "2.3"
BasicModelInterface = "0.1"
CSV = "0.10"
CodecZstd = "0.7, 0.8"
ComponentArrays = "0.13, 0.14, 0.15 - 0.15.22, 0.15"
Configurations = "0.17"
DBInterface = "2.4"
DataFrames = "1.4"
DataInterpolations = "6.5"
DataStructures = "0.18"
Dates = "1"
DiffEqBase = "6.155"
DiffEqCallbacks = "3.6, 4"
EnumX = "1.0"
FiniteDiff = "2.21"
Graphs = "1.9"
HiGHS = "1.7"
IOCapture = "0.2"
IterTools = "1.4"
JuMP = "1.15"
Legolas = "0.5"
LineSearches = "7"
LinearAlgebra = "1"
LinearSolve = "2.24"
Logging = "1"
LoggingExtras = "1"
Makie = "0.21, 0.22"
MetaGraphsNext = "0.6, 0.7"
OrdinaryDiffEqBDF = "1.1"
OrdinaryDiffEqCore = "1.3"
OrdinaryDiffEqLowOrderRK = "1.1"
OrdinaryDiffEqNonlinearSolve = "1.1"
OrdinaryDiffEqRosenbrock = "1.1"
OrdinaryDiffEqSDIRK = "1.1"
OrdinaryDiffEqTsit5 = "1.1"
PreallocationTools = "0.4"
SQLite = "1.5.1"
SciMLBase = "2.36"
SparseArrays = "1"
SparseConnectivityTracer = "0.6.8"
Statistics = "1"
StructArrays = "0.6.13, 0.7"
TOML = "1"
Tables = "1"
TerminalLoggers = "0.1.7"
Test = "1"
TestItemRunner = "1"
TranscodingStreams = "0.9, 0.10, 0.11"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[preferences.LinearSolve]
LoadMKL_JLL = false

[targets]
test = ["Aqua", "CSV", "DataFrames", "IOCapture", "Logging", "Statistics", "TerminalLoggers", "Test", "TOML", "TestItemRunner"]
