version: '2'

services:
  qgis:
    image: qgis/qgis:release-3_34
    container_name: qgis
    volumes:
      - ../ribasim_qgis/:/tests_directory/${PLUGIN_NAME}
    environment:
      - CI=true
      - DISPLAY=:99
    tty: true
