version: '2'

services:
  qgis:
    image: qgis/qgis:release-3_28
    container_name: qgis
    volumes:
      - ../ribasim_qgis/:/tests_directory/${PLUGIN_NAME}
    environment:
      - CI=true
      - DISPLAY=:99
    ulimits:
      stack: 8192 # This sets the stack size to 8MB
