version: '2'

services:
  qgis:
    image: qgis/qgis:release-3_28
    container_name: qgis
    volumes:
      - ../qgis/:/tests_directory/${PLUGIN_NAME}
    environment:
      - CI=true
      - DISPLAY=:99
