starttime = 2019-01-01
endtime = 2019-03-01
# endtime = 2021-01-01

# [s] Î”t for periodic update frequency, including user horizons
update_timestep = 86400
saveat = 86400
save_positions = [true, true]

# optional, default is the path of the TOML
dir_input = "../data/lhm"
dir_output = "../data/lhm"

geopackage = "model.gpkg"
waterbalance = "waterbalance.arrow"

[forcing]
Basin = "forcing.arrow"
